### ISSUE TITLE
Hi There, Any .Net Core support plan?

### ISSUE THREAD

**Issue by rukai-kooboo** [Azure/azure-sdk-for-media-services#173] opened 2016-12-08 08:54 UTC
Hi There, Any .Net Core support plan?

**Comment by TerribleDev** [comment] 2017-05-27 20:26
any updates?

**Comment by shawnmclean** [comment] 2017-06-19 12:14
Is microsoft still supporting this library?

**Comment by adityosnrost** [comment] 2017-07-07 03:17
Any update regarding this feature request ?

**Comment by sbosell** [comment] 2017-08-26 04:10
Same question.  Core 2.0 released.  This library doesn't seem to support it.

**Comment by shawnmclean** [comment] 2017-08-26 04:17
Man, I'm pulling hairs right now trying to get this to work with .net core 2. I got it imported in a .net core 2 project but its complaining about `System.Runtime.Caching`.:

`Could not load file or assembly 'System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`

**Comment by sbosell** [comment] 2017-08-26 04:19
Same here, same error.  I was really surprised to see a lack of support for core.

**Comment by infofromca** [comment] 2017-09-03 16:31
it is said that  core 2.0 can include many many old .net lib, but not this one. the problem is
TransientFaultHandling.Core -Version 5.1.1209.1  , see below

![media-services-core2](https://user-images.githubusercontent.com/297675/30004794-b7581090-90a3-11e7-9a7d-fdddbd0f151f.png)

**Comment by infofromca** [comment] 2017-09-03 16:43
I suggest changing it to
https://github.com/App-vNext/Polly
which is also active

**Comment by infofromca** [comment] 2017-09-16 18:12
{System.TypeInitializationException: The type initializer for 'Microsoft.WindowsAzure.MediaServices.Client.AzureMediaServicesClassFactory' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at Microsoft.WindowsAzure.MediaServices.Client.Cache`1..ctor()
   at Microsoft.WindowsAzure.MediaServices.Client.AzureMediaServicesClassFactory..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.MediaServices.Client.AzureMediaServicesClassFactory.IsAccountCustomHost(String host)
   at Microsoft.WindowsAzure.MediaServices.Client.AzureMediaServicesClassFactory.CreateAzureMediaServicesEndPoint(Uri azureMediaServicesEndpoint, MediaContextBase mediaContext)
   at Microsoft.WindowsAzure.MediaServices.Client.AzureMediaServicesClassFactory..ctor(Uri azureMediaServicesEndpoint, CloudMediaContext mediaContext)
   at Microsoft.WindowsAzure.MediaServices.Client.CloudMediaContext.get_MediaServicesClassFactory()
   at Microsoft.WindowsAzure.MediaServices.Client.ChannelBaseCollection..ctor(MediaContextBase cloudMediaContext)
   at Microsoft.WindowsAzure.MediaServices.Client.CloudMediaContext.get_Channels()
   at Guang.Azure.LiveStream.LiveStreamServices.LiveStreamServiceSyncBase.get_Channels() in E:\orchardCore-beta-zg\Orchard2\src\OrchardCore.Modules\Guang.Azure.LiveStream\LiveStreamServices\LiveStreamServiceSyncBase.cs:line 50
   at Guang.Azure.LiveStream.Drivers.LiveStreamPartDriver.<>c__DisplayClass7_0.<Edit>b__1(LiveStreamViewModel viewModel) in E:\orchardCore-beta-zg\Orchard2\src\OrchardCore.Modules\Guang.Azure.LiveStream\Drivers\LiveStreamPartDriver.cs:line 69
   at OrchardCore.DisplayManagement.Handlers.DisplayDriverBase.<>c__DisplayClass6_0`1.<Shape>b__1(TModel shape) in E:\orchardCore-beta-zg\Orchard2\src\OrchardCore\OrchardCore.DisplayManagement\Handlers\DisplayDriverBase.cs:line 39
   at OrchardCore.DisplayManagement.ShapeFactoryExtensions.<>c__DisplayClass6_0`1.<Create>b__0() in E:\orchardCore-beta-zg\Orchard2\src\OrchardCore\OrchardCore.DisplayManagement\IShapeFactory.cs:line 84
   at OrchardCore.DisplayManagement.Implementation.DefaultShapeFactory.Create(String shapeType, Func`1 shapeFactory, Action`1 creating, Action`1 created) in E:\orchardCore-beta-zg\Orchard2\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultShapeFactory.cs:line 79
   at OrchardCore.DisplayManagement.ShapeFactoryExtensions.Create(IShapeFactory factory, String shapeType, Func`1 shapeFactory) in E:\orchardCore-beta-zg\Orchard2\src\OrchardCore\OrchardCore.DisplayManagement\IShapeFactory.cs:line 71
   at OrchardCore.DisplayManagement.ShapeFactoryExtensions.Create[TShape](IShapeFactory factory, String shapeType, Action`1 initialize) in E:\orchardCore-beta-zg\Orchard2\src\OrchardCore\OrchardCore.DisplayManagement\IShapeFactory.cs:line 81
   at OrchardCore.DisplayManagement.Handlers.DisplayDriverBase.<>c__DisplayClass6_0`1.<Shape>b__0(IBuildShapeContext ctx) in E:\orchardCore-beta-zg\Orchard2\src\OrchardCore\OrchardCore.DisplayManagement\Handlers\DisplayDriverBase.cs:line 39
   at OrchardCore.DisplayManagement.Views.ShapeResult.ApplyImplementation(BuildShapeContext context, String displayType) in E:\orchardCore-beta-zg\Orchard2\src\OrchardCore\OrchardCore.DisplayManagement\Views\ShapeResult.cs:line 98
   at OrchardCore.DisplayManagement.Views.ShapeResult.Apply(BuildEditorContext context) in E:\orchardCore-beta-zg\Orchard2\src\OrchardCore\OrchardCore.DisplayManagement\Views\ShapeResult.cs:line 48
   at OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator.<>c__DisplayClass11_1.<<BuildEditorAsync>b__1>d.MoveNext() in E:\orchardCore-beta-zg\Orchard2\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentItemDisplayCoordinator.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Modules.InvokeExtensions.<InvokeAsync>d__3`1.MoveNext() in E:\orchardCore-beta-zg\Orchard2\src\OrchardCore\OrchardCore.Modules.Abstractions\Extensions\InvokeExtensions.cs:line 78}

**Comment by johndeu** [comment] 2017-10-18 16:59
Yes, officially the problem is the required support for TransientFaultHandling.Core in this SDK, which is not supported in .NET Core. 

We are working on updating our REST API to support Swagger and make some bigger changes to our API (moving to ARM, adding ingest from URL support, and more) and this change will allow us to start auto-generated this .NET SDK using AutoRest going forward. Preview of new API would be sometime early in new year 2018.   We are hoping that the AutoRest project on GitHub will be adding support for .NET Core soon as well. https://github.com/Azure/AutoRest

**Comment by johndeu** [comment] 2017-10-18 17:00
I'm going to close this issue for now, since there is no plan to add .NET Core support to this specific .NET SDK for Media Services. It would come later as stated above.

**Closed by johndeu** 2017-10-18 17:00 UTC

**Comment by shawnmclean** [comment] 2017-10-18 23:16
If anyone wants to use a hacked up wrapper around their REST api, you could use and add to this small project I have: https://github.com/shawnmclean/azure-media-services-core

I have the bare minimum for `Jobs`, `Assets`, `MediaProcessors` and `Locators` for use in my own project.
